baseURL = 'https://abraham-armenta.github.io/valepage/'
languageCode = 'en-us'
title = "PAGINA DE HUGO"
theme = "PaperMod"

# Recomendado para GitHub Pages
publishDir = "public"
canonifyURLs = true

# Opcional pero recomendable para PaperMod
paginate = 5
